fixed stub generation issue that cause NoClassDefFoundError: axis2/apache/org/xsd/*
git-svn-id: https://svn.wso2.org/repos/wso2/trunk/carbon/service-stubs@91928 a5903396-d722-0410-b921-86c7d4935375